server:
  port: 9010
spring:
  application:
    name: pay
  rabbitmq:
    host: 192.168.200.128
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true
wxpay:
  notify_url: http://kylesun.cross.echosite.cn/wxpay/notify #回调地址
alipay:
  notify_url: http://kylesun.cross.echosite.cn/alipay/notify

aLipay:
  #支付宝网关URl
  serverUrl: https://openapi.alipaydev.com/gateway.do
  #应用id
  appId: 2016102900775750
  #商户私钥
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCDIyELc1+lqfTwiub1Hmqwlh4CH4gFWLVX4cmbrGC9VhK4RGLH012zAu1jw35wB6F2gZoJqSalZaLdd67LCBGM4fJRiDt+MoEdDifvXqr0v4njU6yXYpKWM/cpT6JtxhyzCWoq65PN5QtaaLEbAGXPT5Rto91shsKHjBuDHJw63F5H1ZObq1kMe6XoppPRE89FLYkZ75Sj1o78IKJ2g2Ntkm3OBW6Qmba8443Bx+uyqYx7pZTCEuYa6cJQOLyDz9Q/xt1ZdYbCBWoWar1utlhabzMoGYxLlXcwWJEAIWX2jcum14Fthex2ya3bmDuwvJl9LvoNBZU1DEefrdHAtlSdAgMBAAECggEAdsRrGi7M0oJB51U15Yw9vl7HIM8j5wu3ebdxW39cQj5hR+gPusDwnL8q9u7IZXhTwLuSIevDp4qMXZ4WfaV6F6lPSI5kq1/cVc9LVdzcYjvTC0LuDlFlR4oa8JxCFL+XoIMHV4XyYEhv5trog/bxPjfpyv7c/Hx0VEUNacqQqDE9IokrsFEPE3Y37NyNwvv4ZLgsrHSd6ZYNg1YhuRh4gccdk+W9kVwVthJwWL4LmW8qLzDjDGeP7hWnKUllIyZLZfmIBWLou4y5sm3QJ52+GmR+dp5pJbZnA1qHA+hYkb3GfA43U/JLyLSPbTJ0WuaguIRFKv4cK/ODecDhyn/SIQKBgQDOga9hdJjMySEFmOhYE02l+QJKaVeeTxqUdJhVtui+6VF/Ae8RPDnR09yFqDF7mczE3BZZ8wEu20wj5xK/d9Ocr1qI3y/i6iG4W4yyo8GGnClMIFnPelPd+nYMpfa+plXJ8lDNuf2InX2w/sUQsYGCU1L2mU6fLvCIzMywQRV72QKBgQCikR6BOt7Pt3fanV3yUXh+s4LS2BQB++LQD8c/jLJPWbUL9SMuTvjLj9ikp1IgaWr9nvN3xbYrlvlAnZELchgpwuPnjWeqPeu8q+PrFfpGyRDlWzg5HlLMzu9LgBFnLIOWVlkdqcUKgjg0C2kS2Me8WzfB4T4w7TpU4sr/ky04ZQKBgQCraF2oqN1D7hZozPjeUnd7MmtCVJoTn1lSrEzdqMsb3BJ3N6W2SqU7k31Ru8AG9ixPotcypk/vErvqeRzIrK+LOMoPHiJjWS/QFL1+cgpqryhgNeIWI1WFxSVDbmaW7P38eBO2D5FwWjlANthf+Nak1IDii3IFEzM4ebXU/tDUUQKBgASREQtOTQ4GuF4yx33UHg9pGYa0vTMlEUUI/G7jk+q4uWZBl6BoZYLKYqqVbLAuZewD+BDoQ+rLjerrwjRRGy6pI9/QUBYvMR0WswtajbJJWaknu9eW63qHYZ98VIDSdkvV1yEHMNrPt6Z2n5gA8PNwmItguW+EanwR9uPhDYclAoGAEyn0++KUaQ/Gjdb7O41rEmk4txPXe2TLgXYobwJVSEDCjAheSYsPypEpb0vMnpzHwGfFhPgbIqN7U+BlGVJH68lCAS20ht4ioHChqJBJLmyVcKwJzhyexVLES78NqEJh5zomQj/0cUT6o/9EqUxOdktmCaZBco8gw8oF3eNu+40=
  #支付宝公钥
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi8dub/QrchsZZ092GDr525x5LOvN1ojxMnQ9faTCFExNUK+ei2H14Rn3th2LhMMdOU5VfK6YGGHXCKtVWFoda8Uu2LPclMOYto6VTsxXUm83fhhnSkFkAibkzdfubr1f1PZHJ/vISiRSKN3mXfJjMR2imj08IA4byrCF8NgPVmboXwvNeCnjTk4pBkYZOb9dNOWxgZP/pUemaFw2cK3OsFw0ph4NZB0gknUscuEh+huiUQaTT16uxw6ne7AxM18rBrt18etBEwpbgtKhDN9dgvsq2w6AUXy9puIoUuie7bXR7gSYf9uh8XwOMDT4K7bjyo8ljStk9g9OM/HtSKl7mwIDAQAB