server:
  port: 9010
spring:
  application:
    name: pay
  rabbitmq:
    host: 192.168.200.128
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true
wxpay:
  notify_url: http://weizhaohui.cross.echosite.cn/wxpay/notify #回调地址

alipay:
  #支付宝网关URl
  serverUrl: https://openapi.alipaydev.com/gateway.do
  #应用id
  appId: 2016102900775750faTCFExNUK+ei2H14Rn3th2LhMMdOU5VfK6YGGHXCKtVWFoda8Uu2LPclMOYto6VTsxXUm83fhhnSkFkAibkzdfubr1f1PZHJ/vISiRSKN3mXfJjMR2imj08IA4byrCF8NgPVmboXwvNeCnjTk4pBkYZOb9dNOWxgZP/pUemaFw2cK3OsFw0ph4NZB0gknUscuEh+huiUQaTT16uxw6ne7AxM18rBrt18etBEwpbgtKhDN9dgvsq2w6AUXy9puIoUuie7bXR7gSYf9uh8XwOMDT4K7bjyo8ljStk9g9OM/HtSKl7mwIDAQAB
  #商户私钥
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCipjAOSy7TyYZyAEy9NHZRK1Iyo//HHZp0JreKatOhlDslfblzWsu5hVOX/MB46Wkv2s8AY9G8d/iJztTDN5xWtW4Lg8lFgFyPkQLCp+M3bw0tSKP9dBvalUWmtbzJhbEzNt0S8XLPUjHYCGTKa3KIHBHtwLSGS/T+xoOKkXAlXecbk0CRtGRU3MmkKLzlOrzKG4FeTQoCreL6b1AXVdsA3IQxJnsVDo1OL41zqDTFHry2hQIFfmyYHzXEOqh8RwgDmVBAYa4u5f+ffvJrlDdhuPO/6oXmChE/4uMaiLyAV1boanIvanVjkyNZ9z1fu4kaHPZP7UeZ7ZQtqxdy/1JjAgMBAAECggEAbD7t/JVMtOaJ85T/fWxM0fhi3BEJSRsKkAK0ZAp0jjR4qJrjsUHcE7wHxj8QWWf9+TtGSJwmGag+YHimYMXB5nMYqdErQnYLJAD+NU5Gib3+pwSRHz0GzJJLqIeK/RNcuxjoSJMoNZIeWgg8C/s2Xh9QT0rQ2g/zHRxArxfb6wFjXgGkbB9A9MDxk52NU1VU/rtyPsd5EoDqXo36D9WtFOgAQDyUbO79qiRWv/7IZcmJCanMGALrhvGqdS2HNblm8aW/I0OcX4qayMcz15noAJmKwUXT1c6TkDcre1HowrEglWNnFMJvatpPKr6NF9DtaHFRGaUqaq14qR0MLMADAQKBgQDbRveKhbPIWDILc2vJLr60+qHsJWfoxmswPZbLokxVk13Xdc9QyCd+eOnZvLydohJLpQp5lQQlKM21gv+6b1gw4+oJYy63eugPIbiuHjYHc3Klmy1VL0b5RkdA6g1xxoBm9T07+xXZX1eMl1mHtcm1oPZqORxjsMh9mAcSMAcJ/QKBgQC942qs82BSPmSmB1QkcnpKjpSHi5K5Z97LuJIgvLFDcMB5yLHC8WnoLqnOK/6C006nzKAoQ7Aps4OMDB+3kDdb2S1k3M6rXk38Bb7GF/IxRxraGb+CEObplyByv/39yUbcAK0jd+Pkb/wj+NDYR4m+Gb64WbzFA9zyA8OjKVrL3wKBgQCKyu6gZWSYaQq0KMiOvOHFF+cp27tboUvzauhp2D7M48xANreUgDxPVyVdxpL0i8Nc0ghBUMsg4iTiwRow3Y1K1NgsPPUy+b6s5UFKJKE6Mh7dJ82X36bi3VL4ia0c2PIpOQ0bTCBWSHzX5myq86vLJSkTrzaC+0DMDlBbeL7b2QKBgE95L/uEvOqPDIbkiFXcx8wOkqGMS/NnQrsW26nx72rfdN9DnQqPCZlQdmdAyHuuvrvCC8HuWnuJk2P46wljxZeedL5DIAhfJtp0+Rxlh0sSjG1920YvlsVrJ/x+2GnwZMTNT6mJkwrXx7qyd44dmsvCcK0tebEnZcCwzJ+sPkEXAoGAF4Ynx9U6Gd4Gz6AqCkJIcJhk2WgmuwUlsBM7AEW/eiMNRIDqCxyZGINxT5QKZSW0vNUoSrRCzQ4f1CWdS+75H0hXmUVtzkBPaWDmJEFnvF+/Asy8RoM9Wul8+VrplEA+YindRPhWLfsXtbeVXA9hXJv/5xRKzIo3ExJcwiYrWI8=
  #支付宝公钥
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi8dub/QrchsZZ092GDr525x5LOvN1ojxMnQ9